### ISSUE TITLE
🐛: Android Installation Not Working

### ISSUE THREAD

**Issue by luskin** [taplytics/taplytics-react-native#40]
We are unable to install and run Taplytics in our Android project. We know that we properly installed the `taplytics-react-native` package since iOS works as expected.

The [Tapylitics React Native Documentation](https://docs.taplytics.com/docs/react-native-sdk) states that they are RN60+ compatible with autolinking, however we are not finding that to be the case. After several gradle syncs we cannot get Android Studio to see a taplytics package and after attempting to run the project we are receiving the following errors.

## Error
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileStagingDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:stagingDebugCompileClasspath'.
   > Could not find com.taplytics.sdk:taplytics:2.5.0.
     Required by:
         project :app > project :taplytics-react-native
```

#### In the IDE:
<img width="900" alt="Screen Shot 2021-06-29 at 12 35 49 PM" src="https://user-images.githubusercontent.com/5702322/123856944-8b80b100-d8d6-11eb-89ba-34aa50b9d60f.png">

We should not need to install any additional packages if this package is truly RN60+ supported.

#### package.json:
```json
{
   ...
   "react": "16.13.1",
   "react-native": "0.63.4",
   "taplytics-react-native": "^2.1.4",
   ...
}
```

**Comment by nikolasleblanc** [comment]
Hey @luskin, sorry to hear you're having issues. We're actually off today and tomorrow, but I dug into this for you this morning and may have found the issue. It seems as though the custom maven url we try to get gradle to use from within our package is being ignored, and that's why the package isn't being found. When I added it to the project build.gradle file, things started to work.

Can you try adding this to _your_ build.gradle and let me know if that sorts things out for you?

```
maven { url "https://github.com/taplytics/Taplytics-Android-SDK/raw/master/AndroidStudio/" }
```

If this gets you rolling, awesome - we'll do a deeper dive on our end to figure out where/how this went wrong. If it doesn't, send whatever error you encounter and I can take it from there.

**Comment by luskin** [comment]
This works for now, but I'd prefer to see the package work as expected as it's a paid service. Please let me know once this is resolved so we can use auto-linking as it's intended to be used.

**Comment by nikolasleblanc** [comment]
Hey @luskin, I'm going to close the thread for now, but we're looking into getting our SDK hosted more centrally to prevent this type of issue and we'll keep you posted.
